ALTER TABLE "Merchant" ADD COLUMN "freeDeliveryEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Merchant" ADD COLUMN "freeDeliveryKm" DECIMAL(8,3) NOT NULL DEFAULT 0;
ALTER TABLE "Merchant" ADD COLUMN "beyondFreeDeliveryFee" DECIMAL(19,3) NOT NULL DEFAULT 0;
ALTER TABLE "Merchant" ADD COLUMN "maxDeliveryKm" DECIMAL(8,3) NOT NULL DEFAULT 0;
